### ISSUE TITLE
可以搜索某个联系人吗？

### ISSUE THREAD

**Issue by lilongcnc** [hikerpig/lark-space-alfred-workflow#10]
可以搜索某个联系人吗？请问在哪里找到的对应的api呢？

**Comment by hikerpig** [comment]
emm 这个应该需要用飞书开放平台的 API 了，需要一系列登录鉴权操作，搞不动

**Comment by hikerpig** [comment]
我（瞎）猜搜人是这个 API  https://open.larkoffice.com/document/server-docs/contact-v3/user/search-users。 因为没法支持，我这里就把 issue 关了。
