### ISSUE TITLE
看起来返回结构变了

### ISSUE THREAD

**Issue by JiangWeixian** [hikerpig/lark-space-alfred-workflow#2]
![image](https://user-images.githubusercontent.com/6839576/128656878-01f330d5-64f5-4414-922e-64a5c0d4d8ad.png)

**Comment by hikerpig** [comment]
我这边还是好的，难道是你被服务端 AB 到了？
有没有可能是 cookie 过期了？

**Comment by hikerpig** [comment]
@JiangWeixian 更新一下 variables 里的 session 还会有这个问题么？

**Comment by JiangWeixian** [comment]
> @JiangWeixian 更新一下 variables 里的 session 还会有这个问题么？

更新过了

**Comment by hikerpig** [comment]
@JiangWeixian 由于我这里无法重现，可能不是很好帮到你。
1. 你可以魔改一下 lark-search.py 然后 print 出来 data 里都有什么么？
2. 可以直接 lark 我，chenmin.winnie ，发截图之类会方便点

**Comment by JiangWeixian** [comment]
感谢回复，是我的问题，我设置成了 lark-sso-session 了
