### ISSUE TITLE
打开 Doc2.0 URL 地址不正确

### ISSUE THREAD

**Issue by xiaochunjimmy** [hikerpig/lark-space-alfred-workflow#3]
1. Doc2.0 的打开 URL 不正确，需要手动移除 URL 中的 `space/`才行，可否更新优化一下？
2. 可否针对 Doc、Doc2.0、Sheet、Bitable 等不同类型的文档展示不同的图标样式？目前在检索结果里，都是相同的图标，不太容易区分

**Comment by hikerpig** [comment]
已 Lark 联系 😅
