### ISSUE TITLE
Feature Request: 支持通过变量传入 python 解释器路径

### ISSUE THREAD

**Issue by hikerpig** [hikerpig/lark-space-alfred-workflow#5]
此脚本依赖 python2 ，但一些人默认 PATH 下的 python 是 python3 ，同时也有通过 pyenv 等安装的不在 PATH 里。
可否支持通过 pythonExcutable 来配置 python2 的位置？

<img width="799" alt="image" src="https://user-images.githubusercontent.com/2259688/170441188-f11f86b0-ff11-4b93-bd99-7524559138be.png">

**Comment by ChasLui** [comment]
可以看看这个就是将$NODE_PATH作为变量
https://github.com/zeronight/feishu-docs-workflow

**Comment by hikerpig** [comment]
@ChasLui 涨知识了，Thanks♪(･ω･)ﾉ。我这周研究下。应该问题不大。

**Comment by hikerpig** [comment]
[0.4.2](https://github.com/hikerpig/lark-space-alfred-workflow/releases/tag/v0.4.2) 上了一个变量 `pythonPath`， 可以试试。 在 README 最底下有例子。
