### ISSUE TITLE
lkc    File "lark-list-doc-types.py", line 17, in <module>     'arg': DocType.DOCX, AttributeError: class DocType has no attribute 'DOCX'

### ISSUE THREAD

**Issue by augusl** [hikerpig/lark-space-alfred-workflow#6]

**Comment by hikerpig** [comment]
@augusl Sorry about this, it turns out that I made a mistake when exporting the workflow. I've updated the workflow asset in v0.4.2 release, you can download and install it to see if it's OK.

https://github.com/hikerpig/lark-space-alfred-workflow/releases/tag/v0.4.2

**Comment by augusl** [comment]
> @augusl Sorry about this, it turns out that I made a mistake when exporting the workflow. I've updated the workflow asset in v0.4.2 release, you can download and install it to see if it's OK.
> 
> https://github.com/hikerpig/lark-space-alfred-workflow/releases/tag/v0.4.2

It's OK
